(in-package #:schema-protocol-toml)

(defun %ht (&rest plist)
  (let ((ht (make-hash-table :test #'equal)))
    (loop for (k v) on plist by #'cddr
          when v
            do (setf (gethash (if (stringp k) k (string-downcase (symbol-name k))) ht) v))
    ht))

(defun %set (table key value)
  (when value
    (setf (gethash key table) value))
  table)

(defun type-name (class)
  (string-downcase (symbol-name (class-name class))))

(defun enum-wire (value)
  (etypecase value
    (keyword (string-downcase (symbol-name value)))
    (symbol (string-downcase (symbol-name value)))
    (string value)
    (number value)
    (character (string value))))

(defun or-null-p (spec)
  (and (eq (type-kind spec) :or)
       (some (lambda (s) (eq (type-kind s) :null)) (type-args spec))))

(defun or-payload (spec)
  (find-if (lambda (s) (not (eq (type-kind s) :null))) (type-args spec)))

(defun integer-bounds (spec slot)
  (let ((args (and (consp spec) (eq (type-kind spec) :integer) (rest spec))))
    (values (or (and slot (slot-minimum slot))
                (and args (not (eq (first args) '*)) (first args)))
            (or (and slot (slot-maximum slot))
                (and (rest args) (not (eq (second args) '*)) (second args))))))

(defun ensure-type (class types)
  (let ((key (type-name class)))
    (unless (gethash key types)
      (setf (gethash key types) (make-hash-table :test #'equal))
      (setf (gethash key types) (object-tosd class types)))
    key))

(defun type-tosd (spec slot types)
  (let ((kind (type-kind spec)))
    (when (or-null-p spec)
      (return-from type-tosd (type-tosd (or-payload spec) slot types)))
    (ecase kind
      (:any (%ht "type" "any"))
      (:null (%ht "type" "string" "optional" t))
      (:string
       (let ((ht (%ht "type" "string")))
         (%set ht "minlength" (and slot (slot-min-length slot)))
         (%set ht "maxlength" (and slot (slot-max-length slot)))
         (when (and slot (slot-format slot))
           (setf (gethash "format" ht)
                 (string-downcase (symbol-name (slot-format slot)))))
         (when (and slot (slot-pattern slot) (stringp (slot-pattern slot)))
           (setf (gethash "pattern" ht) (slot-pattern slot)))
         (when (and slot (slot-description slot))
           (setf (gethash "description" ht) (slot-description slot)))
         ht))
      ((:integer)
       (let ((ht (%ht "type" "integer")))
         (multiple-value-bind (lo hi) (integer-bounds spec slot)
           (%set ht "min" lo)
           (%set ht "max" hi))
         ht))
      ((:number :real :float)
       (let ((ht (%ht "type" "float")))
         (%set ht "min" (and slot (slot-minimum slot)))
         (%set ht "max" (and slot (slot-maximum slot)))
         ht))
      (:boolean (%ht "type" "boolean"))
      ((:keyword :symbol) (%ht "type" "string"))
      (:hash-table (%ht "type" "table"))
      (:member
       (let ((vals (map 'vector #'enum-wire (type-args spec)))
             (ht (%ht "type" "string")))
         (setf (gethash "allowedvalues" ht) vals)
         ht))
      (:enum
       (let ((ht (%ht "type" "string")))
         (setf (gethash "allowedvalues" ht)
               (map 'vector #'enum-wire (enum-members spec)))
         ht))
      (:eql
       (let ((ht (%ht "type" "string")))
         (setf (gethash "allowedvalues" ht) (vector (enum-wire (second spec))))
         ht))
      (:satisfies (%ht "type" "any"))
      (:lisp (%ht "type" "any"))
      (:or
       (let ((ht (make-hash-table :test #'equal)))
         (setf (gethash "oneof" ht)
               (map 'vector
                    (lambda (s)
                      (let ((node (type-tosd s slot types)))
                        (or (%get node "type") "any")))
                    (type-args spec)))
         ht))
      ((:vector :list :sequence)
       (let ((ht (%ht "type" "array"))
             (elt (sequence-element-type spec slot)))
         (%set ht "minlength" (and slot (slot-min-length slot)))
         (%set ht "maxlength" (and slot (slot-max-length slot)))
         (when elt
           (let ((item (type-tosd elt slot types)))
             (setf (gethash "itemtype" ht)
                   (or (%get item "type") "any"))))
         ht))
      (:nested
       (let ((key (ensure-type (find-schema spec) types)))
         (%ht "type" (format nil "types.~A" key)))))))

(defun object-tosd (class types)
  (finalize-schema class)
  (let ((ht (%ht "type" "table")))
    (dolist (slot (schema-slots class))
      (when (and (slot-wire-p slot) (slot-dump-p slot))
        (let* ((key (slot-wire-key slot class))
               (node (type-tosd (slot-definition-type slot) slot types)))
          (unless (slot-is-required-p slot)
            (setf (gethash "optional" node) t))
          (setf (gethash key ht) node))))
    ht))

(defun emit-class (schema &key (version +tosd-version+))
  (let* ((class (schema-of schema))
         (types (make-hash-table :test #'equal))
         (elements (object-tosd class types)))
    (remhash "type" elements)
    (let ((root (make-hash-table :test #'equal)))
      (setf (gethash "toml-schema" root) (%ht "version" version))
      (when (plusp (hash-table-count types))
        (setf (gethash "types" root) types))
      (setf (gethash "elements" root) elements)
      root)))

(defun emit (schema &key (as :table) (version +tosd-version+))
  "SCHEMA-CLASS / name / instance / document → TOSD hash-table or TOML string."
  (let ((table (cond
                 ((toml-schema-document-p schema)
                  (stringify-toml (toml-schema-table schema)))
                 ((hash-table-p schema)
                  (stringify-toml schema))
                 (t (emit-class schema :version version)))))
    (ecase as
      (:table table)
      ((:toml :string) (toml-protocol:encode table)))))
